### PR TITLE
Run the full test suite on macOS

### PR DESCRIPTION
**Pull request by jakirkham**
Replaces PR ( https://github.com/conda-forge/python-spams-feedstock/pull/16 )

These test were failing on macOS so they were skipped. Here we re-enable them on macOS to see if we can get them to pass. This will run the full test suite on macOS just like what is currently done on Linux.

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like the tests now work on macOS. However it looks like it will take too long to run them all.

**Comment by jakirkham** [comment]
Should add am really confused as to how the macOS builds take so much longer than the Linux ones.

**Comment by samuelstjean** [comment]
Way to revive old stuff, but I think the mac stuff is much slower because it does not link correctly to openmp and they are not parallel for the most part because of that (but some lin algebra parts are with openblas). Or at least on computers here it looks like that, maybe, making the mac version run about 4x slower.

**Comment by jakirkham** [comment]
Thanks for pinging this, @samuelstjean, and the advice.

We just made some changes to how this builds with PR ( https://github.com/conda-forge/python-spams-feedstock/pull/25 ) recently. In particular macOS now builds with Clang, which includes OpenMP support. It was building with an older GCC that had GOMP previously. Given this, have rebased this PR to see if we get better results.

**Comment by samuelstjean** [comment]
Wee, seems like it indeed did it, that new version seems to be a tad faster (~ 1.5x) to run the test suite, thanks.

**Pull request merged**
