### PR TITLE
Update patches to fix None comparisons

### PR DESCRIPTION
**Pull request by jakirkham**
There were some comparisons to `None` that used `==`/`!=`. While this can work, it is generally recommended that one use `is`/`is not` for these comparisons. As `is`/`is not` are identity comparisons, this is most likely faster as well.

Normally it wouldn't be worthwhile to update the patches like this. However some of these comparisons are with NumPy arrays. As of NumPy 1.13, using `==`/`!=` with `None` now computes [element-wise comparisons]( https://github.com/numpy/numpy/blob/v1.13.0/doc/release/1.13.0-notes.rst#futurewarning-to-changed-behavior ). Thus if a `bool` were expected before like in an `if` clause, now a NumPy Array is returned. The result is this broke a lot of conditionals in SPAMS. Hence some more aggressive patching was required.

While not all of these are arrays, it was much easier and safer to simply fix all comparisons to `None` so as to use `is`/`is not`. After all, the results will be exactly the same for all other non-array variables.

Have bumped the build number as well to get a fresh build. This will also remove a fair number of warnings with older NumPy versions (pre-1.13).

### CODE REVIEW

**Comment by jakirkham** [comment]
@zym1010, do you mind looking over these patches? We need them for NumPy 1.13. Basically did find and replace. Still they are quite large and it would be nice to have another set of eyes on them.

**Comment by zym1010** [comment]
@jakirkham  no problem. will have a look tomorrow.

**Comment by zym1010** [comment]
@jakirkham BTW, in numpy 1.13, does all None count as NaN?

**Comment by jakirkham** [comment]
Thanks.

> BTW, in numpy 1.13, does all None count as NaN?

How do you mean?

If one compares `nan` to `None`, that will be False. Though I guess that is true of `nan == nan` as well.

However if you assign `None`, then that will replace the value by `nan` if the array is at least of a real type. It is an error on integral types. On `bool` arrays, setting a value to `None` makes it `False`.

Though this happens even in NumPy 1.11. Not sure when it started to be the case.

>  anyway, so previously, `!= None` and `==None` actually is equivalent to `is None`, and `is not None`, right?

Exactly. This merely preserves the old behavior on the new NumPy (or the old NumPy for that matter).

**Comment by zym1010** [comment]
@jakirkham  I think it might be easiest to simply use their latest version on <https://gforge.inria.fr/frs/?group_id=3975>, released on 6-6 (currently, it's python 3 only). In that version, it fixed most of `None` issue, although some are still left. But it would be much easier to work on that one.

**Comment by zym1010** [comment]
@jakirkham  Anyway, I have checked the patches, and they look good to me.

**Comment by jakirkham** [comment]
Thanks @zym1010.

Yeah I emailed upstream yesterday about issue ( https://github.com/conda-forge/python-spams-feedstock/issues/17 ) amongst other things. I do hope we can find a reasonable solution.

Am not sure how to get these patches or the existing ones upstream. Do you know if we can get access to their GitLab repo? If not, I might need to rehost on GitHub just to compile the patches into some PR that can more easily be absorbed upstream.

Would you be ok if we go ahead with these patches for now?

**Comment by zym1010** [comment]
> Would you be ok if we go ahead with these patches for now?

@jakirkham yeah go ahead.

> Am not sure how to get these patches or the existing ones upstream

The gitlab one is at <https://gitlab.inria.fr/thoth/spams-devel>. I think it's public for cloning.

**Comment by jakirkham** [comment]
Thanks.

Yeah, I'll look into getting an account.

**Pull request merged**
