### PR TITLE
Release 2.6

### PR DESCRIPTION
**Pull request by jakirkham**
Also adds support for Python 3.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please take a look @samuelstjean @zym1010. Would appreciate your feedback.

**Comment by jakirkham** [comment]
If there is no other feedback, I plan on merging this in the next day.

**Comment by zym1010** [comment]
@jakirkham  sorry got quite busy these days. As a practitioner for using spams, I think it will be all good if your current build can pass all the tests. Is that true?

**Comment by jakirkham** [comment]
Running the test suite is a good idea. Though we aren't doing that currently. I had encountered some issues getting it to run without crashing before. That said, definitely worth trying to get it to run again.

Tried to do this today. Took some more patching because of type issues in the test suite (`float`s used for dimensions of NumPy arrays). Also some tests appear to fail on macOS due to memory issues in OpenBLAS. We will likely need to rebuild OpenBLAS to fix that. Have run as much of the test suite as possible on macOS and Linux. Please see PR ( https://github.com/conda-forge/python-spams-feedstock/pull/13 ) for details.

**Comment by jakirkham** [comment]
Have rebased this after merging the additional tests. Required a few more patches to handle Python 2 and 3 differences for existing patches that the test suite required (type issues mainly). Mostly straightforward. Seems to build and pass. Any other thoughts @zym1010?

**Comment by zym1010** [comment]
@jakirkham great. I think it's good to go.

**Comment by jakirkham** [comment]
Thanks @zym1010. Merged!

**Comment by zym1010** [comment]
@jakirkham  thanks! I will test it out soon.

**Pull request merged**
